apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: user

  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: vaheeddockerhub/ecomm-user:latest   # 🔥 your built image
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8003

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "300m"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user

  ports:
    - port: 80
      targetPort: 8003
      protocol: TCP

  type: ClusterIP
